# https://www.kaggle.com/datasets/umuttuygurr/e-commerce-fraud-detection-dataset

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import polars as pl
import polars.selectors as cs
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
import great_tables as tg
import datetime as dt
import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTE

In [2]:
df_path = r'/Users/zygimantas/Documents/Data_sets/transactions.csv'

In [3]:
df = pl.read_csv(df_path, infer_schema_length=10_000)

In [4]:
df.null_count()

shape: (1, 17)
┌────────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transactio ┆ user_id ┆ account_ag ┆ total_tra ┆ … ┆ three_ds_ ┆ transacti ┆ shipping_ ┆ is_fraud │
│ n_id       ┆ ---     ┆ e_days     ┆ nsactions ┆   ┆ flag      ┆ on_time   ┆ distance_ ┆ ---      │
│ ---        ┆ u32     ┆ ---        ┆ _user     ┆   ┆ ---       ┆ ---       ┆ km        ┆ u32      │
│ u32        ┆         ┆ u32        ┆ ---       ┆   ┆ u32       ┆ u32       ┆ ---       ┆          │
│            ┆         ┆            ┆ u32       ┆   ┆           ┆           ┆ u32       ┆          │
╞════════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0          ┆ 0       ┆ 0          ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└────────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.select(
    df.select(
        cs.string().n_unique()
    )
)

shape: (1, 5)
┌─────────┬─────────────┬─────────┬───────────────────┬──────────────────┐
│ country ┆ bin_country ┆ channel ┆ merchant_category ┆ transaction_time │
│ ---     ┆ ---         ┆ ---     ┆ ---               ┆ ---              │
│ u32     ┆ u32         ┆ u32     ┆ u32               ┆ u32              │
╞═════════╪═════════════╪═════════╪═══════════════════╪══════════════════╡
│ 10      ┆ 10          ┆ 2       ┆ 5                 ┆ 297975           │
└─────────┴─────────────┴─────────┴───────────────────┴──────────────────┘

In [6]:
df.collect_schema()

Schema([('transaction_id', Int64),
        ('user_id', Int64),
        ('account_age_days', Int64),
        ('total_transactions_user', Int64),
        ('avg_amount_user', Float64),
        ('amount', Float64),
        ('country', String),
        ('bin_country', String),
        ('channel', String),
        ('merchant_category', String),
        ('promo_used', Int64),
        ('avs_match', Int64),
        ('cvv_result', Int64),
        ('three_ds_flag', Int64),
        ('transaction_time', String),
        ('shipping_distance_km', Float64),
        ('is_fraud', Int64)])

In [7]:
df = df.with_columns(
    pl.col('transaction_time').str.strptime(pl.Datetime, '%Y-%m-%dT%H:%M:%SZ')
)

In [10]:
df.select(
    cs.all().shrink_dtype()
).estimated_size('mb')

13.834456443786621

In [11]:
df.select(
    cs.all()
).estimated_size('mb')

33.8412561416626